# Generated by Django 6.0.3 on 2026-03-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_menuitem_order_notification_orderitem_vendorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='google_maps_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
