# Generated by Codex on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username_ascii'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('STUDENT_REGISTER', 'Student registration'), ('STAFF_APPLICATION', 'Staff application')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=10)),
                ('target', models.CharField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='contactotp',
            index=models.Index(fields=['purpose', 'channel', 'target', '-created_at'], name='users_conta_purpose_2ee8db_idx'),
        ),
    ]
