# Generated by Django 6.0.3 on 2026-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_payment_razorpay_refund_id_payment_refund_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID used for payment request (e.g., user@oksbi)', max_length=50),
        ),
    ]
